apiVersion: topolvm.cybozu.com/v2
kind: TopolvmCluster
metadata:
  name: topolvmcluster-sample
  # namespace must be the same with topolvm-operator
  namespace: nativestor-system
spec:
  # Add fields here
  topolvmVersion: quay.io/topolvm/topolvm-with-sidecar:0.10
  # Certs secret must contain a tls certificate and key which will be used by the topolvm-controller
  # certsSecret: mutatingwebhook
  storage:
    useAllNodes: false
    useAllDevices: false
    useLoop: false
    volumeGroupName: "hdd"
    className: "hdd"
    devices:
      - name: "/dev/sdb"
        type: "disk"
      - name: "/dev/loop2"
        type: "loop"
        auto: false
      - name: "loop1"
        type: "loop"
        auto: true
        path: "/data"
        size: 100  #unit G

    deviceClasses:
        # kubernetes node name
      - nodeName: "192.168.16.98"
        # node classes
        classes:
          # node class name
          - className: "hdd"
            # user should specific volume group name , operator will create it
            volumeGroup: "test"
            # a node must a class should set default, when StorageClass not specific device class name , the default class will be used
            default: true
            # available devices used for creating volume group
            devices:
              - name: "/dev/sdb"
                type: "disk"
              - name: "/dev/loop2"
                type: "loop"
                auto: false
              - name: "loop1"
                type: "loop"
                auto: true
                path: "/data"
                size: 100  #unit G