name: Origin
on:
  pull_request:
  push:
    branches:
      - 'origin-topolvm'
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: make setup
      - run: make check-uncommitted
      - run: make build
      - run: make test
      - run: make image
  e2e-k8s:
    name: e2e-k8s
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        test_kubernetes_target: [current, prev]
    env:
      TEST_KUBERNETES_TARGET: ${{ matrix.test_kubernetes_target }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: make -C e2e setup
      - run: make -C e2e test